In [1]:
import numpy as np

In [2]:
np.random.rand(1,10)

array([[0.30555448, 0.85822465, 0.22935112, 0.55874619, 0.2702047 ,
        0.5831292 , 0.94538233, 0.28687075, 0.44261827, 0.81391971]])

In [11]:
results1 = []
results2 = []
dim = 10000
for i in range(10000):
    x = np.random.rand(1,dim)
    y = np.random.rand(1,dim)
    d2 = np.sqrt(np.dot((x-y),(x-y).T))
    d1 = np.sum(np.abs(x-y))
    results1 += [d1]
    results2 += [d2]
np.mean(results1), np.mean(results2)

(np.float64(3333.673354765676), np.float64(40.82745925031578))

In [4]:
x = np.random.rand(1,dim)
y = np.random.rand(1,dim)
d = np.linalg.norm(x-y,1)

In [5]:
x

array([[0.94753918, 0.45917957, 0.39130243, ..., 0.66794609, 0.97551016,
        0.58267442]])

In [6]:
y

array([[0.4510633 , 0.3172191 , 0.97534958, ..., 0.09476196, 0.39179538,
        0.62071422]])

In [7]:
d

np.float64(0.9901930862525526)

In [8]:
x-y

array([[ 0.49647588,  0.14196047, -0.58404715, ...,  0.57318414,
         0.58371478, -0.0380398 ]])