# Perceptron learning

In [1]:
import numpy as np
from matplotlib import pyplot as plt

Perceptron learning is an iterative algorithm that converges to the appropriate weights for a single perceptron, given a learnable training set. If the training set is not learnable, the algorithm will not converge.

**Perceptron Learning Algorithm**

Given a dataset $X$ of $m$ observations $x \in \mathcal{R}^{1 \times n}$, an outcome vector $y \in \mathcal{R}^{m \times 1}$, we wish to find a weight vector $w \in \mathcal{R}^{n \times 1}$ such that $y_i = A(\mathbf{x}_i \cdot \mathbf{w})$ for each $0 \leq i < m$. In matrix form: $A(\mathbf{X} \mathbf{w}) = \mathbf{y}$. The last element of each observation vector $\mathbf{x}$ will be -1 to account for the bias term.

1. Initialize $ \mathbf{w} $ as a random vector.
2. **For each epoch**:
    - For each $ (\mathbf{x}_i, y_i)$ in the training set:
      - Compute $ \hat{y} = A(\mathbf{x}_i \cdot \mathbf{w}) $.
      - Update $ \mathbf{w} $ as:
        $$
        \mathbf{w} \leftarrow \mathbf{w} + (y_i - \hat{y}) \lambda \mathbf{x}_i
        $$
3. Compute accuracy:
   $$
   \text{accuracy} = 1 - \frac{\sum_i |f(\mathbf{x}_i) - A(\mathbf{x}_i \cdot \mathbf{w})|}{\text{len}(\text{training\_set})}
   $$
4. Return $ (\mathbf{w}, \text{accuracy}) $.

The learning rate $\lambda$ determines the rate of convergence. In practice $\lambda$ can be close to, but not greater than, 1.

We'll define the data set as a matrix $X$ and a vector $y$ using numpy. 

In [2]:
## The dataset corresponding to boolean AND. 

X = np.array([
    [0, 0, -1],
    [0, 1, -1],
    [1, 0, -1],
    [1, 1, -1]
])
y = np.array([[0, 0, 0, 1]])

In [3]:
## The heaviside step function

def A(x):
    return np.heaviside(x,0)

In [4]:
w = np.random.random((3,1))

In [6]:
r = 0.1
for j in range(100):
    i = j%4
    x = X[i:i+1]
    fx = y[0,i]
    y_hat = A(x @ w)
    w = w + r*(fx - y_hat)*x.T

for j in range(4):
    i = j%4
    x = X[i:i+1]
    fx = y[0,i]
    y_hat = A(x @ w)
    print(x, y_hat)

[[ 0  0 -1]] [[0.]]
[[ 0  1 -1]] [[0.]]
[[ 1  0 -1]] [[0.]]
[[ 1  1 -1]] [[1.]]


In [7]:
w = np.random.random((3,1))
all_w = []
r = 1
for epoch in range(200):
    for i in range(4):
        x = X[i:i+1]
        fx = y[0,i]
        y_hat = A(x @ w)
        w = w + r*(fx - y_hat)*x.T
        all_w += [w[0:2]]
    accuracy = 1 - np.sum(np.abs(A(X@w)  - y.T))/4


In [8]:
def boolean_function(n, vars):
    result = []
    while n>0 or vars > 0:
        result += [n % 2]
        n = n // 2
        vars -= 1
    result.reverse()
    return result

In [9]:
boolean_function(1293,6)

[1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1]

In [10]:
def make_ds(n):
    X = []
    Y = []
    for i in range(2**n):
        X += [boolean_function(i,n)+[-1]]
    for i in range(2**(2**n)):
        Y += [boolean_function(i,2**n)]
    return np.array(X), Y

In [42]:
def learn(X,y,lr):
    w = np.random.random((X.shape[1],1))
    all_w = []
    r = 1
    for epoch in range(100):
        for i in range(X.shape[0]):
            x = X[i:i+1]
            fx = y[0,i]
            y_hat = A(x @ w)
            w = w + lr*(fx - y_hat)*x.T
            all_w += [w[0:2]]
        accuracy = 1 - np.sum(np.abs(A(X@w)  - y.T))/4
    return accuracy == 1.0

In [43]:
n = 2
X, Y = make_ds(n)
for i in range(2**(2**n)):
    print(i,learn(X, np.array([Y[i]]), 1.0))

0 True
1 True
2 True
3 True
4 True
5 True
6 False
7 True
8 True
9 False
10 True
11 True
12 True
13 True
14 True
15 True


In [44]:
n = 3
X, Y = make_ds(n)
count = 0
for i in range(2**(2**n)):
    result = learn(X, np.array([Y[i]]),1.0)
    if (result == True):
        count+=1
print(count)

104


In [45]:
n = 4
X, Y = make_ds(n)
count = 0
for i in range(2**(2**n)):
    result = learn(X, np.array([Y[i]]),1.0)
    if (result == True):
        count+=1
print(count)

1882
